import { useMemo, useRef, useState } from "react";
import { ArrowRight, Check, ChevronRight, ExternalLink, FileText, GraduationCap, Search, Sparkles, Upload } from "lucide-react";
import { useLocation } from "wouter";
import { careerCatalog, defaultCareerPath, getCareerPath, type CareerPathId } from "@/data/careerCatalog";
import HanaGameFrame from "@/components/HanaGameFrame";
import LearningResources from "@/components/LearningResources";

const universities = [
  { name: "Harvard Computer Science", curriculum: "https://csadvising.seas.harvard.edu/concentration/requirements/" },
  { name: "MIT Computer Science", curriculum: "https://catalog.mit.edu/degree-charts/computer-science-engineering-course-6-3/" },
  { name: "Stanford Computer Science", curriculum: "https://www.cs.stanford.edu/bs-degree-requirements" },
] as const;
const featuredPathIds: CareerPathId[] = ["computer-science", "software-engineering", "ai-ml", "data-science", "cybersecurity", "web-fullstack"];
type CurriculumResult = { answer?: string; sources?: { title: string; url: string }[]; error?: string; accessFailed?: boolean };

export default function CareerPath() {
  const [, navigate] = useLocation();
  const uploadRef = useRef<HTMLInputElement>(null);
  const [selectedPath, setSelectedPath] = useState<CareerPathId>(() => { if (typeof window === "undefined") return defaultCareerPath; const saved = window.localStorage.getItem("hana-career-path"); return saved && careerCatalog.some(p => p.id === saved) ? saved as CareerPathId : defaultCareerPath; });
  const [stageIndex, setStageIndex] = useState(0); const [showAll, setShowAll] = useState(false); const [search, setSearch] = useState("");
  const [university, setUniversity] = useState(() => { if (typeof window === "undefined") return universities[0].name; const saved = window.localStorage.getItem("hana-university"); return universities.some(item => item.name === saved) ? saved! : universities[0].name; });
  const [manualCurriculum, setManualCurriculum] = useState(""); const [showManual, setShowManual] = useState(false); const [curriculumLoading, setCurriculumLoading] = useState(false); const [curriculumResult, setCurriculumResult] = useState<CurriculumResult | null>(null); const [adjustPrompt, setAdjustPrompt] = useState(false);
  const path = getCareerPath(selectedPath); const stage = path.stages[Math.min(stageIndex, path.stages.length - 1)]; const firstSkill = path.skills.find(skill => stage?.skills.includes(skill.name)) ?? path.skills[0];
  const visiblePaths = useMemo(() => { const pool = showAll ? careerCatalog : careerCatalog.filter(p => featuredPathIds.includes(p.id)); const needle = search.trim().toLowerCase(); return needle ? pool.filter(p => `${p.title} ${p.shortTitle} ${p.description} ${p.roles.join(" ")}`.toLowerCase().includes(needle)) : pool; }, [showAll, search]);
  const selectedUniversity = universities.find(item => item.name === university) ?? universities[0];
  const choose = (id: CareerPathId) => { setSelectedPath(id); setStageIndex(0); setCurriculumResult(null); setAdjustPrompt(false); window.localStorage.setItem("hana-career-path", id); };
  const chooseUniversity = (name: string) => { setUniversity(name); window.localStorage.setItem("hana-university", name); setCurriculumResult(null); setAdjustPrompt(false); };
  const readCurriculumFile = async (file: File) => { try { const text = await file.text(); setManualCurriculum(text.slice(0, 30000)); setShowManual(true); setCurriculumResult({ answer: `Loaded ${file.name}. Review the text below, then choose Compare my uploaded curriculum.` }); } catch { setCurriculumResult({ error: "Hana couldn't read that file. Please paste the curriculum text manually instead." }); } };
  const checkCurriculum = async (manual = false) => {
    if (manual && manualCurriculum.trim().length < 30) { setCurriculumResult({ error: "Paste or upload at least a short curriculum outline so Hana has something meaningful to compare." }); return; }
    setCurriculumLoading(true); setCurriculumResult(null); setAdjustPrompt(false);
    try {
      const response = await fetch("/api/curriculum-check", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ careerPath: path.title, stage: stage.title, skills: stage.skills, curriculumUrl: manual ? "" : selectedUniversity.curriculum, university: university || "My university", manualCurriculum: manual ? manualCurriculum : "" }) });
      const data = await response.json() as CurriculumResult; if (!response.ok) throw new Error(data.error ?? "Curriculum check failed"); setCurriculumResult(data);
    } catch (error) { setCurriculumResult({ error: error instanceof Error ? error.message : "Curriculum check is unavailable right now." }); }
    finally { setCurriculumLoading(false); }
  };

  return <HanaGameFrame title={`${path.title} · Roadmap`}>
    <div className="grid min-w-0 gap-5 lg:grid-cols-[1.02fr_.98fr]">
      <section className="min-w-0 overflow-hidden rounded-[30px] border border-white/10 bg-white/[.055] shadow-xl backdrop-blur"><div className="flex items-center justify-between gap-3 border-b border-white/10 px-5 py-4 sm:px-6"><div className="min-w-0"><p className="text-xs font-bold uppercase tracking-[.14em] text-white/40">Choose your direction</p><h2 className="mt-1 break-words font-display text-2xl font-semibold">{path.shortTitle} · one journey</h2></div><Sparkles className="h-5 w-5 shrink-0 text-[#f1c77b]"/></div><div className="grid min-w-0 gap-2 p-4 sm:grid-cols-2">{visiblePaths.map(item => <button key={item.id} onClick={() => choose(item.id)} className={`min-w-0 rounded-2xl border p-3 text-left transition ${selectedPath === item.id ? "border-[#f1c77b]/60 bg-[#f1c77b]/10" : "border-white/10 bg-white/[.03] hover:bg-white/[.07]"}`}><div className="flex items-start justify-between gap-2"><span className="break-words text-sm font-semibold">{item.title}</span>{selectedPath===item.id&&<Check className="h-4 w-4 shrink-0 text-[#f1c77b]"/>}</div><span className="mt-1 block break-words text-xs leading-5 text-white/45">{item.description}</span></button>)}</div><div className="flex min-w-0 gap-2 border-t border-white/10 p-4"><div className="relative min-w-0 flex-1"><Search className="pointer-events-none absolute left-3 top-1/2 h-4 w-4 -translate-y-1/2 text-white/30"/><input value={search} onChange={e=>{setSearch(e.target.value);setShowAll(true)}} placeholder="Search a direction…" className="w-full rounded-full border border-white/10 bg-black/10 py-2.5 pl-9 pr-4 text-sm text-white outline-none placeholder:text-white/30"/></div><button onClick={()=>setShowAll(v=>!v)} className="shrink-0 rounded-full border border-white/10 bg-white/[.04] px-4 text-sm font-semibold">{showAll?"Fewer":"All"}</button></div></section>
      <section className="min-w-0 rounded-[30px] border border-white/10 bg-white/[.055] p-5 shadow-xl backdrop-blur sm:p-6"><div className="flex min-w-0 items-start justify-between gap-3"><div className="min-w-0"><p className="text-xs font-bold uppercase tracking-[.14em] text-[#f1c77b]/75">World {stageIndex+1} of {path.stages.length}</p><h2 className="mt-2 break-words font-display text-3xl font-semibold">{stage.world}</h2><p className="mt-1 break-words text-lg font-semibold text-white/80">{stage.title}</p></div><span className="shrink-0 rounded-full border border-white/10 bg-white/5 px-3 py-1 text-xs text-white/50">Quest step</span></div><p className="mt-5 break-words text-sm leading-6 text-white/60">{stage.outcome}</p><div className="mt-4 flex flex-wrap gap-2">{stage.skills.map(skill=><span key={skill} className="rounded-full border border-white/10 bg-white/5 px-3 py-1.5 text-xs font-semibold text-white/70">{skill}</span>)}</div><div className="mt-6 grid min-w-0 gap-2">{path.stages.map((item,index)=><button key={item.world} onClick={()=>{setStageIndex(index);setCurriculumResult(null)}} className={`flex min-w-0 items-center gap-3 rounded-2xl border p-3 text-left ${index===stageIndex?"border-[#f1c77b]/50 bg-[#f1c77b]/10":"border-white/10 bg-white/[.03]"}`}><span className="flex h-8 w-8 shrink-0 items-center justify-center rounded-full bg-white/10 text-xs font-bold">{String(index+1).padStart(2,"0")}</span><span className="min-w-0 flex-1"><span className="block break-words text-xs uppercase tracking-[.12em] text-white/35">{item.world}</span><span className="mt-1 block break-words text-sm font-semibold">{item.title}</span></span><ChevronRight className="h-4 w-4 shrink-0 text-white/30"/></button>)}</div><button onClick={()=>navigate("/chat?prompt="+encodeURIComponent(`I'm at the ${stage.world} stage of ${path.title}. Help me understand this stage and what I should do first.`))} className="mt-5 inline-flex min-h-10 items-center gap-2 rounded-full bg-[#f1c77b] px-5 py-3 font-bold text-[#172630]">Ask Hana about this step <ArrowRight className="h-4 w-4"/></button></section>
    </div>
    <div className="mt-5"><LearningResources skill={firstSkill?.name ?? stage.skills[0] ?? path.title} skills={stage.skills} university={selectedUniversity} /></div>
    <section className="mt-5 min-w-0 rounded-[30px] border border-white/10 bg-white/[.055] p-5 shadow-xl backdrop-blur sm:p-6"><div className="flex min-w-0 flex-col gap-5 md:flex-row md:items-start md:justify-between"><div className="min-w-0 max-w-2xl"><p className="text-xs font-bold uppercase tracking-[.14em] text-white/40">Optional university curriculum check</p><h2 className="mt-2 break-words font-display text-2xl font-semibold">Check the official curriculum — then ask you.</h2><p className="mt-2 break-words text-sm leading-6 text-white/50">Choose a real university CS degree curriculum. Hana checks that official page first. If access fails, paste or upload the curriculum manually. Your roadmap is never changed automatically.</p></div><GraduationCap className="h-6 w-6 shrink-0 text-[#f1c77b]"/></div>
      <div className="mt-5 grid min-w-0 gap-3 md:grid-cols-[1fr_auto] md:items-center"><select value={university} onChange={e=>chooseUniversity(e.target.value)} className="min-w-0 rounded-2xl border border-white/10 bg-[#132434] px-4 py-3 text-sm text-white outline-none">{universities.map(u=><option key={u.name}>{u.name}</option>)}</select><div className="flex min-w-0 flex-wrap gap-2"><a href={selectedUniversity.curriculum} target="_blank" rel="noopener noreferrer" className="inline-flex min-h-10 min-w-0 items-center justify-center gap-2 rounded-full border border-white/10 bg-white px-4 py-3 text-sm font-semibold text-[#172630]">Open official curriculum <ExternalLink className="h-4 w-4 shrink-0"/></a><button onClick={()=>void checkCurriculum(false)} disabled={curriculumLoading} className="inline-flex min-h-10 items-center justify-center gap-2 rounded-full bg-[#f1c77b] px-5 py-3 font-bold text-[#172630]">{curriculumLoading?"Hana is checking…":"Check curriculum fit"}<Sparkles className="h-4 w-4 shrink-0"/></button></div></div>
      <div className="mt-4 min-w-0 rounded-2xl border border-white/10 bg-black/10 p-4"><div className="flex min-w-0 flex-wrap items-center gap-2"><button onClick={()=>setShowManual(v=>!v)} className="inline-flex min-h-10 items-center gap-2 text-sm font-semibold text-white/70"><FileText className="h-4 w-4 shrink-0 text-[#f1c77b]"/>{showManual ? "Hide manual curriculum" : "Can't access your curriculum? Paste it manually"}</button><button onClick={()=>uploadRef.current?.click()} className="inline-flex min-h-10 items-center gap-2 rounded-full border border-white/10 bg-white/5 px-3 py-2 text-xs font-semibold text-white/65"><Upload className="h-3.5 w-3.5"/>Upload text curriculum</button><input ref={uploadRef} type="file" accept=".txt,.md,.csv,.json" className="hidden" onChange={e=>{const file=e.target.files?.[0]; if(file) void readCurriculumFile(file); e.currentTarget.value=""}}/></div>{showManual && <div className="mt-3"><textarea value={manualCurriculum} onChange={e=>setManualCurriculum(e.target.value)} rows={7} placeholder="Paste the course list, curriculum outline, or syllabus here…" className="w-full min-w-0 rounded-2xl border border-white/10 bg-[#132434] p-4 text-sm leading-6 text-white outline-none placeholder:text-white/30"/><button onClick={()=>void checkCurriculum(true)} disabled={curriculumLoading || manualCurriculum.trim().length<30} className="mt-3 min-h-10 rounded-full bg-[#f1c77b] px-4 py-2.5 text-sm font-bold text-[#172630]">Compare my pasted/uploaded curriculum</button></div>}</div>
      {curriculumResult?.answer && <div className="mt-5 min-w-0 rounded-2xl border border-[#f1c77b]/30 bg-[#f1c77b]/10 p-4"><p className="break-words whitespace-pre-wrap text-sm leading-6 text-white/80">{curriculumResult.answer}</p>{curriculumResult.sources?.length ? <div className="mt-3 flex min-w-0 flex-wrap gap-2">{curriculumResult.sources.slice(0,4).map(source=><a key={source.url} href={source.url} target="_blank" rel="noopener noreferrer" className="max-w-full break-words rounded-full border border-white/10 bg-white/5 px-3 py-1.5 text-xs font-semibold text-white/65 underline">{source.title}</a>)}</div>:null}<p className="mt-4 text-sm font-semibold text-white">Would you like Hana to adjust this roadmap?</p><div className="mt-3 flex flex-wrap gap-2"><button onClick={()=>setAdjustPrompt(true)} className="min-h-10 rounded-full bg-[#f1c77b] px-4 py-2 text-sm font-bold text-[#172630]">Yes, show adjustments</button><button onClick={()=>setCurriculumResult(null)} className="min-h-10 rounded-full border border-white/10 px-4 py-2 text-sm font-semibold">Keep my roadmap</button></div></div>}
      {curriculumResult?.error && <div className="mt-5 min-w-0 rounded-2xl border border-white/10 bg-white/5 p-4 text-sm text-white/60"><p className="break-words">{curriculumResult.error}</p><button onClick={()=>setShowManual(true)} className="mt-3 min-h-10 font-semibold text-[#f1c77b] underline">Paste the curriculum manually</button></div>}
      {curriculumResult?.accessFailed && !curriculumResult?.answer && <div className="mt-4 rounded-2xl border border-[#f1c77b]/30 bg-[#f1c77b]/10 p-4 text-sm text-white/70">Hana couldn't reliably access that curriculum. Please paste or upload the curriculum above so she can compare it instead of guessing.</div>}
      {adjustPrompt && <div className="mt-4 min-w-0 rounded-2xl border border-[#f1c77b]/30 bg-[#f1c77b]/10 p-4 text-sm"><p className="break-words font-semibold">Great. Hana will propose only the smallest useful changes. Your roadmap is still unchanged.</p><button onClick={()=>navigate(`/chat?prompt=${encodeURIComponent(`I chose to adjust my ${path.title} roadmap. Compare the ${stage.title} stage with the official ${selectedUniversity.name} curriculum${manualCurriculum ? ` I pasted or uploaded: ${manualCurriculum.slice(0,3000)}` : ` at ${selectedUniversity.curriculum}`}. Propose the smallest useful adjustments, show what changes and why, and do not apply them automatically.`)}`)} className="mt-3 min-h-10 rounded-full bg-[#f1c77b] px-4 py-2 text-sm font-bold text-[#172630]">Open adjustment plan in Hana</button></div>}
    </section>
    <section className="mt-5 grid min-w-0 gap-3 sm:grid-cols-3"><button onClick={()=>navigate("/projects")} className="min-w-0 rounded-2xl border border-white/10 bg-white/[.055] p-5 text-left transition hover:bg-white/[.09]"><p className="font-semibold">Projects</p><p className="mt-1 break-words text-sm text-white/45">Turn this skill into something you can show.</p></button><button onClick={()=>navigate("/opportunities")} className="min-w-0 rounded-2xl border border-white/10 bg-white/[.055] p-5 text-left transition hover:bg-white/[.09]"><p className="font-semibold">Opportunities</p><p className="mt-1 break-words text-sm text-white/45">Find current opportunities.</p></button><button onClick={()=>navigate("/research?query="+encodeURIComponent(path.title))} className="min-w-0 rounded-2xl border border-white/10 bg-white/[.055] p-5 text-left transition hover:bg-white/[.09]"><p className="font-semibold">Research field</p><p className="mt-1 break-words text-sm text-white/45">Search current resources and universities.</p></button></section>
  </HanaGameFrame>;
}