import { ArrowRight, BookOpen, BriefcaseBusiness, Compass, MessageCircle, Rocket, Search, Sparkles } from "lucide-react";
import { Link } from "wouter";
import { careerCatalog, defaultCareerPath, type CareerPathId } from "@/data/careerCatalog";

const worlds = [
  ["Origin Village", "/assets/worlds/origin-village.svg", "Choose a direction"],
  ["Code Forge", "/assets/worlds/code-forge.svg", "Learn the foundations"],
  ["Webwilds", "/assets/worlds/webwilds.svg", "Make something useful"],
  ["Skyforge", "/assets/worlds/skyforge.svg", "Build and ship"],
  ["Beacon Summit", "/assets/worlds/beacon-summit.svg", "Show your work"],
] as const;

export default function CareerHub() {
  const saved = typeof window !== "undefined" ? window.localStorage.getItem("hana-career-path") : null;
  const selected = careerCatalog.find(p => p.id === saved) ?? careerCatalog.find(p => p.id === defaultCareerPath) ?? careerCatalog[0];
  const date = new Intl.DateTimeFormat(undefined, { weekday: "long", month: "long", day: "numeric" }).format(new Date());
  return <main className="min-h-screen bg-[#FBF7F1] text-[#2d3c39]"><header className="sticky top-0 z-40 border-b border-[#eadfd3] bg-[#FBF7F1]/90 backdrop-blur-xl"><div className="mx-auto flex max-w-7xl items-center justify-between px-5 py-3 md:px-8"><Link href="/" className="font-display text-xl font-bold">HANA</Link><nav className="hidden gap-2 md:flex"><Link href="/path" className="rounded-full px-3 py-2 text-sm font-semibold hover:bg-white">Roadmap</Link><Link href="/projects" className="rounded-full px-3 py-2 text-sm font-semibold hover:bg-white">Projects</Link><Link href="/opportunities" className="rounded-full px-3 py-2 text-sm font-semibold hover:bg-white">Opportunities</Link><Link href="/research" className="rounded-full px-3 py-2 text-sm font-semibold hover:bg-white">Research</Link><Link href="/chat" className="rounded-full bg-[#315d58] px-4 py-2 text-sm font-semibold text-white">Ask Hana</Link></nav><Link href="/path" className="rounded-full border border-[#dfd3c7] bg-white px-3 py-2 text-xs font-semibold md:hidden">Change path</Link></div></header>
  <section className="mx-auto grid max-w-7xl gap-8 px-5 py-8 md:px-8 lg:grid-cols-[1.08fr_.92fr]"><div className="flex flex-col justify-center"><span className="w-fit rounded-full border border-[#e8ddd1] bg-white px-3 py-2 text-xs font-bold uppercase tracking-[.14em]">{date}</span><p className="mt-6 text-xs font-bold uppercase tracking-[.16em] text-[#9b8e80]">Hana · your next chapter</p><h1 className="mt-2 max-w-2xl font-display text-5xl font-semibold leading-[1.02] tracking-[-.055em] sm:text-6xl">Welcome to your {selected.shortTitle} adventure.</h1><p className="mt-5 max-w-xl text-lg leading-8 text-[#76695d]">You don't need to understand the whole career yet. Hana keeps the full route ready and brings forward one useful next step.</p><div className="mt-8 flex flex-wrap gap-3"><Link href="/path" className="inline-flex items-center gap-2 rounded-full bg-[#315d58] px-5 py-3.5 font-semibold text-white shadow-lg">Continue my roadmap <ArrowRight className="h-4 w-4"/></Link><Link href="/chat" className="inline-flex items-center gap-2 rounded-full border border-[#dfd3c7] bg-white px-5 py-3.5 font-semibold"><MessageCircle className="h-4 w-4"/> Talk to Hana</Link></div></div><div className="relative flex min-h-[520px] items-center justify-center overflow-hidden rounded-[2.5rem] bg-[#142737] p-5 shadow-[0_30px_90px_rgba(49,44,35,.18)]"><img src="/assets/hana-phase1-approved-opening.png" alt="Hana" className="relative z-10 max-h-[570px] w-full object-contain"/></div></section>
  <section className="mx-auto max-w-7xl px-5 pb-10 md:px-8"><div className="mb-5 flex items-end justify-between"><div><p className="text-xs font-bold uppercase tracking-[.16em] text-[#9b8e80]">Your world</p><h2 className="mt-2 font-display text-3xl font-semibold">Five worlds that make the roadmap feel like an adventure.</h2></div><Compass className="h-5 w-5 text-[#6ca595]"/></div><div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-5">{worlds.map(([name,image,text])=><div key={name} className="overflow-hidden rounded-[24px] border border-[#e5dbcf] bg-white shadow-sm"><img src={image} alt="" className="h-28 w-full object-contain"/><div className="p-4"><p className="font-semibold">{name}</p><p className="mt-1 text-sm text-[#76695d]">{text}</p></div></div>)}</div></section>
  <section className="border-y border-[#eadfd3] bg-white/70"><div className="mx-auto max-w-7xl px-5 py-10 md:px-8"><p className="text-xs font-bold uppercase tracking-[.16em] text-[#9b8e80]">Keep the mountain hidden</p><h2 className="mt-2 font-display text-3xl font-semibold">What can Hana do for you?</h2><div className="mt-5 grid gap-4 md:grid-cols-2 lg:grid-cols-4"><Link href="/path" className="rounded-[24px] border border-[#e7ddd2] bg-[#fffdf9] p-5 shadow-sm"><Compass className="h-5 w-5 text-[#4f806f]"/><h3 className="mt-4 font-semibold">Personal roadmap</h3><p className="mt-2 text-sm text-[#76695d]">See the full route only when you want it.</p></Link><Link href="/projects" className="rounded-[24px] border border-[#e7ddd2] bg-[#fffdf9] p-5 shadow-sm"><Rocket className="h-5 w-5 text-[#db8b71]"/><h3 className="mt-4 font-semibold">One project</h3><p className="mt-2 text-sm text-[#76695d]">Turn the next skill into something you can show.</p></Link><Link href="/opportunities" className="rounded-[24px] border border-[#e7ddd2] bg-[#fffdf9] p-5 shadow-sm"><BriefcaseBusiness className="h-5 w-5 text-[#9d8cc2]"/><h3 className="mt-4 font-semibold">Opportunities</h3><p className="mt-2 text-sm text-[#76695d]">Find programs that fit instead of racing a countdown.</p></Link><Link href="/research" className="rounded-[24px] border border-[#e7ddd2] bg-[#fffdf9] p-5 shadow-sm"><Search className="h-5 w-5 text-[#4f806f]"/><h3 className="mt-4 font-semibold">Research a field</h3><p className="mt-2 text-sm text-[#76695d]">Search the web, watch tutorials, compare universities.</p></Link></div><div className="mt-5 rounded-[26px] border border-[#e4d9cc] bg-[#f7f1e9] p-5"><div className="flex items-start gap-4"><div className="rounded-2xl bg-white p-3"><Sparkles className="h-5 w-5 text-[#db8b71]"/></div><div><p className="font-semibold">Currently exploring: {selected.title}</p><p className="mt-1 text-sm text-[#76695d]">{selected.roles.slice(0,3).join(" · ")}</p><p className="mt-3 text-sm text-[#76695d]">Learning resources are attached to the skills in your path, with alternatives so one unavailable link never blocks you.</p></div></div></div></div></section></main>;
}
