import { useState } from "react";
import { ArrowRight, BookOpen, CheckCircle2, ExternalLink, Github, HeartHandshake, Layers3, MessageCircle, Send, Sparkles, Trophy } from "lucide-react";

const ART = "/assets/hana-phase1-approved-opening.png";
const links = [
  ["CS50x", "https://cs50.harvard.edu/x/"],
  ["MDN Web Docs", "https://developer.mozilla.org/en-US/docs/Learn_web_development"],
  ["Python Tutorial", "https://docs.python.org/3/tutorial/"],
  ["GitHub Skills", "https://skills.github.com/"],
  ["freeCodeCamp", "https://www.freecodecamp.org/learn/"],
  ["Hugging Face Learn", "https://huggingface.co/learn"],
] as const;
const missions = [
  "Understand how REST APIs help apps talk to each other.",
  "Make your first GitHub proof commit.",
  "Build one useful UI component.",
] as const;

function reply(text: string) {
  const q = text.toLowerCase();
  if (q.includes("api")) return "Think of an API like a waiter: your app asks for something, the API carries the request, and a service sends data back. Start with one GET request and inspect the response.";
  if (q.includes("github")) return "Make one small public proof: a clean README, a meaningful commit, and a short note explaining what you learned.";
  if (q.includes("project")) return "Build the smallest useful version first. Then add one feature that proves the skill you want employers to see.";
  if (q.includes("stuck") || q.includes("overwhelm") || q.includes("confused")) return "Pick one tiny next step. Spend 20 focused minutes on it, then come back with the exact point that blocked you.";
  if (q.includes("career") || q.includes("learn next")) return "For software engineering: programming fundamentals → Git/GitHub → web + APIs → databases → deployment → portfolio projects.";
  return "I’m Hana 🌿 Tell me what you’re learning, what you’re building, or exactly where you’re stuck, and I’ll turn it into a next step.";
}

export default function EmergencyHana() {
  const [view, setView] = useState("home");
  const [completed, setCompleted] = useState(0);
  const [mission, setMission] = useState(0);
  const [input, setInput] = useState("");
  const [messages, setMessages] = useState([
    { role: "hana", text: "Hi, I’m Hana 🌿 What would feel most useful right now?" },
  ]);
  const go = (next: string) => { setView(next); window.scrollTo({ top: 0, behavior: "smooth" }); };
  const send = (value = input) => {
    const text = value.trim();
    if (!text) return;
    setInput("");
    setMessages(old => [...old, { role: "user", text }, { role: "hana", text: reply(text) }]);
  };
  return (
    <div className="min-h-screen bg-[#07151d] text-[#f8f1e7]">
      <div className="fixed inset-0 -z-0 bg-cover bg-center" style={{ backgroundImage: `linear-gradient(110deg,rgba(4,15,22,.95) 8%,rgba(6,24,31,.76) 46%,rgba(5,15,23,.42) 78%),url('${ART}')` }} />
      <div className="fixed inset-0 -z-0 bg-[radial-gradient(circle_at_72%_32%,rgba(180,255,220,.16),transparent_25%),linear-gradient(180deg,transparent,rgba(1,7,12,.72))]" />
      <header className="relative z-10 flex items-center justify-between border-b border-white/10 bg-[#061720]/70 px-4 py-4 backdrop-blur-xl md:px-8">
        <button onClick={() => go("home")} className="flex items-center gap-3 text-left"><span className="grid h-10 w-10 place-items-center rounded-2xl bg-white/10"><Sparkles className="h-5 w-5 text-[#d9f1cb]" /></span><span><span className="block font-display text-2xl font-semibold">HANA</span><span className="block text-[10px] uppercase tracking-[.18em] text-white/40">Your CS adventure</span></span></button>
        <nav className="hidden gap-2 md:flex">{[["Roadmap", "roadmap", CompassIcon], ["Projects", "projects", Layers3], ["Opportunities", "opportunities", Trophy], ["Ask Hana", "chat", MessageCircle]].map(([label,id,Icon]) => <button key={id as string} onClick={() => go(id as string)} className="rounded-full border border-white/10 bg-white/5 px-4 py-2 text-sm font-semibold text-white/70 hover:bg-white/10"><Icon className="mr-1 inline h-4 w-4" />{label as string}</button>)}</nav>
        <button onClick={() => go(view === "chat" ? "home" : "chat")} className="rounded-full border border-white/10 bg-white/10 px-4 py-2 text-sm font-semibold md:hidden">{view === "chat" ? "Home" : "Ask Hana"}</button>
      </header>

      <main className="relative z-10 mx-auto max-w-6xl px-4 py-8 md:px-8 md:py-12">
        {view === "home" && <section><div className="max-w-3xl pt-4 md:pt-12"><p className="text-xs font-bold uppercase tracking-[.2em] text-[#d8efcb]">A personal computer science adventure</p><h1 className="mt-4 font-display text-5xl font-semibold leading-[.95] tracking-[-.06em] md:text-7xl">Learn one small thing.<br />Build something real.<br /><span className="text-[#d8efcb]">Find your next step.</span></h1><p className="mt-6 max-w-2xl text-base leading-7 text-white/65 md:text-lg">Hana turns the huge CS journey into clear missions, real resources, projects, opportunities, and a calm place to ask for help.</p><div className="mt-8 flex flex-wrap gap-3"><button onClick={() => go("roadmap")} className="rounded-full bg-[#d8efcb] px-6 py-3 text-sm font-bold text-[#17312d]">START JOURNEY <ArrowRight className="ml-1 inline h-4 w-4" /></button><button onClick={() => go("chat")} className="rounded-full border border-white/15 bg-white/10 px-6 py-3 text-sm font-bold">ASK HANA <MessageCircle className="ml-1 inline h-4 w-4" /></button></div></div><div className="mt-12 grid gap-4 md:grid-cols-3">{[[BookOpen,"Daily missions","One focused next action instead of a giant to-do list."],[Layers3,"Build proof","Projects and GitHub evidence attached to learning."],[Trophy,"Find opportunities","Hackathons, open source, fellowships and career paths."]].map(([Icon,title,text]) => <article key={title as string} className="rounded-[26px] border border-white/10 bg-[#071b25]/75 p-5 backdrop-blur-xl"><div className="grid h-11 w-11 place-items-center rounded-2xl bg-white/10"><Icon className="h-5 w-5 text-[#d8efcb]" /></div><h2 className="mt-4 font-display text-2xl font-semibold">{title as string}</h2><p className="mt-2 text-sm leading-6 text-white/55">{text as string}</p></article>)}</div></section>}
        {view === "roadmap" && <section><p className="text-xs font-bold uppercase tracking-[.18em] text-[#d8efcb]">World 01 · Navigation</p><h1 className="mt-2 font-display text-4xl font-semibold md:text-6xl">Follow the glowing path.</h1><p className="mt-3 max-w-2xl text-white/60">Five connected worlds take you from foundations to portfolio-ready work.</p><div className="mt-8 grid gap-4">{[["01","Origin Village","Computer Science Foundations","Python · Git · problem solving",true],["02","Code Forge","Programming & Problem Solving","Functions · data structures · debugging",completed>=1],["03","Weblands","Web Development","HTML · CSS · JavaScript · APIs",completed>=2],["04","Cloudspire","Backend & Cloud","Databases · deployment · reliability",completed>=3],["05","Summit of Builders","Career & Opportunities","Portfolio · open source · opportunities",completed>=4]].map((item,i)=><button key={item[0] as string} disabled={!item[4]} onClick={()=>setMission(i%missions.length)} className={`rounded-[28px] border p-5 text-left ${item[4]?"border-white/10 bg-[#071b25]/75 hover:bg-[#0c2630]":"border-white/5 bg-black/20 opacity-50"}`}><div className="flex items-start gap-4"><div className="grid h-12 w-12 place-items-center rounded-2xl bg-white/10 font-display">{item[4]?item[0]:"🔒"}</div><div><span className="text-[11px] font-bold uppercase tracking-[.12em] text-[#d8efcb]/70">{item[1] as string}</span><h2 className="mt-2 font-display text-2xl font-semibold">{item[2] as string}</h2><p className="mt-2 text-sm text-white/55">{item[3] as string}</p></div></div></button>)}</div><div className="mt-6 rounded-[28px] border border-[#d8efcb]/20 bg-[#d8efcb]/8 p-5"><p className="text-xs font-bold uppercase tracking-[.14em] text-[#d8efcb]">Today’s mission · {missions[mission]}</p><p className="mt-2 text-sm text-white/60">Learn one idea, try one small action, then build proof.</p><button onClick={()=>{setCompleted(c=>Math.min(5,c+1));go("projects")}} className="mt-4 rounded-full bg-[#d8efcb] px-5 py-2.5 text-sm font-bold text-[#17312d]">Complete mission <CheckCircle2 className="ml-1 inline h-4 w-4" /></button></div></section>}
        {view === "projects" && <section><p className="text-xs font-bold uppercase tracking-[.18em] text-[#d8efcb]">World 02 · Guild workshop</p><h1 className="mt-2 font-display text-4xl font-semibold md:text-6xl">Build proof, one checkpoint at a time.</h1><div className="mt-8 grid gap-5 md:grid-cols-2"><article className="rounded-[28px] border border-white/10 bg-[#071b25]/75 p-6 backdrop-blur-xl"><p className="text-xs font-bold uppercase tracking-[.14em] text-white/40">Active project</p><h2 className="mt-3 font-display text-3xl font-semibold">Weather & discovery app</h2><p className="mt-3 text-sm leading-6 text-white/55">Practice APIs, UI design, error handling, and GitHub evidence.</p><div className="mt-6 h-2 rounded-full bg-white/10"><div className="h-full w-[46%] rounded-full bg-[#d8efcb]" /></div><p className="mt-2 text-xs text-white/40">46% · current checkpoint: connect the first GET request</p><a href="https://github.com/ismatfida1/hana-career-companion" target="_blank" rel="noreferrer" className="mt-5 inline-flex rounded-full border border-white/10 bg-white/5 px-4 py-2 text-sm font-semibold">HANA GitHub <Github className="ml-1 h-4 w-4" /></a></article><article className="rounded-[28px] border border-white/10 bg-[#071b25]/75 p-6 backdrop-blur-xl"><p className="text-xs font-bold uppercase tracking-[.14em] text-white/40">Proof checklist</p><div className="mt-4 grid gap-3">{["Write a clean README","Make one meaningful commit","Document what the API returns","Share a short reflection"].map((x,i)=><div key={x} className="flex items-center gap-3 rounded-2xl bg-white/5 p-3"><span className="grid h-7 w-7 place-items-center rounded-full bg-white/10 text-xs">{i<2?"✓":i+1}</span><span className="text-sm text-white/65">{x}</span></div>)}</div></article></div></section>}
        {view === "opportunities" && <section><p className="text-xs font-bold uppercase tracking-[.18em] text-[#d8efcb]">World 03 · Adventurer’s Board</p><h1 className="mt-2 font-display text-4xl font-semibold md:text-6xl">Find a quest with a reason.</h1><p className="mt-3 max-w-2xl text-white/60">Hackathons, open source, fellowships, internships, volunteering, and research—connected to your learning path.</p><div className="mt-8 grid gap-4 md:grid-cols-3">{[["Hackathons","Build under a deadline and learn by doing."],["Open source","Practice GitHub collaboration and real contribution."],["Fellowships","Find mentorship, community, and career exposure."]].map(([title,text])=><article key={title} className="rounded-[28px] border border-white/10 bg-[#071b25]/75 p-6 backdrop-blur-xl"><Trophy className="h-6 w-6 text-[#d8efcb]" /><h2 className="mt-4 font-display text-2xl font-semibold">{title}</h2><p className="mt-2 text-sm leading-6 text-white/55">{text}</p><a href="https://github.com/explore" target="_blank" rel="noreferrer" className="mt-4 inline-flex text-sm font-semibold text-[#d8efcb]">Explore <ExternalLink className="ml-1 h-4 w-4" /></a></article>)}</div></section>}
        {view === "chat" && <section className="mx-auto max-w-5xl"><p className="text-xs font-bold uppercase tracking-[.18em] text-[#d8efcb]">World 04 · Hana’s study</p><h1 className="mt-2 font-display text-4xl font-semibold md:text-6xl">Ask Hana anything.</h1><div className="mt-7 grid gap-5 lg:grid-cols-[1fr_280px]"><section className="flex min-h-[560px] flex-col rounded-[28px] border border-white/10 bg-[#061720]/80 p-4 backdrop-blur-xl md:p-6"><div className="flex items-center gap-3 border-b border-white/10 pb-4"><span className="grid h-10 w-10 place-items-center rounded-2xl bg-white/10"><HeartHandshake className="h-5 w-5 text-[#d8efcb]" /></span><div><p className="font-semibold">Hana</p><p className="text-xs text-white/40">Career companion · ready</p></div><span className="ml-auto h-2 w-2 rounded-full bg-[#d8efcb]" /></div><div className="flex-1 space-y-4 overflow-y-auto py-5">{messages.map((m,i)=><div key={i} className={`flex ${m.role==="user"?"justify-end":"justify-start"}`}><div className={`max-w-[88%] rounded-[20px] px-4 py-3 text-sm leading-6 ${m.role==="user"?"bg-[#d8efcb] text-[#17312d]":"bg-white/7 text-white/75"}`}>{m.text}</div></div>)}</div><div className="mb-3 flex flex-wrap gap-2">{["Explain APIs simply","What should I learn next?","I’m stuck on my project"].map(p=><button key={p} onClick={()=>send(p)} className="rounded-full border border-white/10 bg-white/5 px-3 py-1.5 text-xs font-semibold text-white/65">{p}</button>)}</div><div className="flex items-end gap-3 rounded-[20px] border border-white/10 bg-white/5 p-2"><textarea value={input} onChange={e=>setInput(e.target.value)} onKeyDown={e=>{if(e.key==="Enter"&&!e.shiftKey){e.preventDefault();send()}}} placeholder="Tell Hana what’s on your mind…" className="min-h-[58px] flex-1 resize-none border-0 bg-transparent p-2 text-sm outline-none placeholder:text-white/30" /><button onClick={()=>send()} className="rounded-2xl bg-[#d8efcb] p-3 text-[#17312d]"><Send className="h-4 w-4" /></button></div></section><aside className="rounded-[28px] border border-white/10 bg-[#071b25]/75 p-5 backdrop-blur-xl"><p className="text-xs font-bold uppercase tracking-[.14em] text-white/40">Starter resources</p><div className="mt-4 grid gap-2">{links.map(([title,url])=><a key={title} href={url} target="_blank" rel="noreferrer" className="rounded-2xl bg-white/5 p-3 hover:bg-white/10"><p className="text-sm font-semibold">{title}</p><p className="mt-1 text-[11px] text-white/35">Open <ExternalLink className="ml-1 inline h-3 w-3" /></p></a>)}</div><a href="https://github.com/ismatfida1/hana-career-companion" target="_blank" rel="noreferrer" className="mt-4 inline-flex text-sm font-semibold text-[#d8efcb]">HANA source <Github className="ml-1 h-4 w-4" /></a></aside></div></section>}
      </main>
    </div>
  );
}

function CompassIcon(props: { className?: string }) { return <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" className={props.className}><circle cx="12" cy="12" r="9"/><path d="m15 9-2.5 5.5L7 17l2.5-5.5L15 9Z"/></svg>; }
