import { ArrowRight, BriefcaseBusiness, ExternalLink, HeartHandshake, Sparkles, Search, RefreshCw, CheckCircle2 } from "lucide-react";
import { useEffect, useState } from "react";
import { useLocation } from "wouter";
import HanaGameFrame from "@/components/HanaGameFrame";

type Opportunity = { title: string; description: string; url: string; why: string; source?: string; free?: boolean; deadline?: string; eligibility?: string };
const sources: Opportunity[] = [
  { title: "Devpost Hackathons", description: "Browse current hackathons and filter for events with no entry fee.", url: "https://devpost.com/hackathons", why: "Strong place to find build-focused competitions.", source: "Devpost", free: true },
  { title: "Google for Developers", description: "Explore Google's developer community events and programs.", url: "https://developers.google.com/community", why: "Useful for Google ecosystem learning and community opportunities.", source: "Google", free: true },
  { title: "GitHub Explore", description: "Discover open-source projects and communities for visible engineering practice.", url: "https://github.com/explore", why: "Useful for building public engineering experience.", source: "GitHub", free: true },
  { title: "Major League Hacking", description: "Explore student hackathons and developer community opportunities.", url: "https://mlh.io/seasons/2026/events", why: "Useful for student-focused hackathon discovery.", source: "MLH", free: true },
];

export default function Opportunities() {
  const [, navigate] = useLocation(); const [query, setQuery] = useState(""); const [items, setItems] = useState<Opportunity[]>(sources); const [loading, setLoading] = useState(false); const [updated, setUpdated] = useState(false);
  const find = async () => { setLoading(true); try { const q = query.trim() || "latest free entry hackathons competitions scholarships developer programs for computer science students"; const r = await fetch(`/api/opportunities?q=${encodeURIComponent(q)}`); const d = await r.json() as { opportunities?: Opportunity[] }; if (d.opportunities?.length) setItems(d.opportunities.filter(item => item.free !== false)); setUpdated(true); } catch { setItems(sources); } finally { setLoading(false); } };
  useEffect(() => { void find(); }, []);
  return <HanaGameFrame title="Opportunities · Find your opening">
    <section className="rounded-[30px] border border-white/10 bg-white/[.055] p-5 shadow-xl backdrop-blur sm:p-6"><div className="flex items-start gap-3"><Search className="h-6 w-6 text-[#f1c77b]"/><div className="flex-1"><p className="text-xs font-bold uppercase tracking-[.16em] text-white/40">Beacon Summit · Live quest board</p><h2 className="mt-1 font-display text-2xl font-semibold">Find opportunities that are actually open.</h2><p className="mt-2 text-sm leading-6 text-white/50">Hana searches current web sources and asks for free-entry opportunities. Always verify the official page before applying because eligibility and deadlines change.</p><div className="mt-4 flex flex-col gap-3 sm:flex-row"><input value={query} onChange={e=>setQuery(e.target.value)} onKeyDown={e=>e.key==='Enter'&&void find()} placeholder="AI hackathons, Google programs, cybersecurity competitions…" className="flex-1 rounded-2xl border border-white/10 bg-black/10 px-4 py-3 text-white outline-none placeholder:text-white/30"/><button onClick={()=>void find()} disabled={loading} className="inline-flex items-center justify-center gap-2 rounded-2xl bg-[#f1c77b] px-5 py-3 font-bold text-[#172630]"><RefreshCw className={`h-4 w-4 ${loading?'animate-spin':''}`}/>{loading?"Checking…":"Find latest"}</button></div></div></div>{updated&&<p className="mt-3 text-xs text-white/35">Quest board refreshed. Results are screened for free-entry intent; verify the official page for final eligibility and fee details.</p>}</section>
    <section className="mt-5 grid gap-4 md:grid-cols-2">{items.map(item=><article key={item.url} className="rounded-[28px] border border-white/10 bg-white/[.055] p-5 shadow-xl backdrop-blur sm:p-6"><div className="flex items-center justify-between"><div className="rounded-2xl bg-[#f1c77b] p-3 text-[#172630]"><BriefcaseBusiness className="h-5 w-5"/></div><div className="flex items-center gap-2 text-xs font-bold uppercase tracking-wide text-emerald-300"><CheckCircle2 className="h-4 w-4"/>Free-entry quest</div></div><p className="mt-4 text-xs font-bold uppercase tracking-[.14em] text-white/35">{item.source ?? "Web source"}</p><h2 className="mt-2 font-display text-2xl font-semibold">{item.title}</h2><p className="mt-2 text-sm leading-6 text-white/55">{item.description}</p>{item.deadline&&<p className="mt-3 text-xs font-semibold text-white/60">Deadline: {item.deadline}</p>}{item.eligibility&&<p className="mt-1 text-xs text-white/45">Eligibility: {item.eligibility}</p>}<div className="mt-4 rounded-2xl border border-white/10 bg-black/10 p-3 text-sm text-white/65"><strong className="text-white">Why Hana recommends it:</strong> {item.why}</div><div className="mt-5 flex flex-wrap gap-2"><a href={item.url} target="_blank" rel="noreferrer" className="inline-flex items-center gap-2 rounded-full bg-[#f1c77b] px-4 py-2.5 text-sm font-bold text-[#172630]">Open official source <ExternalLink className="h-4 w-4"/></a><button onClick={()=>navigate(`/chat?prompt=${encodeURIComponent(`Research this opportunity deeply: ${item.title} ${item.url}. Check current deadline, eligibility, location/online status, entry fee, theme, required skills, and whether it fits my career path. Only recommend it if the entry is free.`)}`)} className="inline-flex items-center gap-2 rounded-full border border-white/10 px-4 py-2.5 text-sm font-semibold text-white/70"><Sparkles className="h-4 w-4"/>Ask Hana to verify</button></div></article>)}</section>
    <section className="mt-5 rounded-[30px] border border-white/10 bg-white/[.055] p-6 shadow-xl backdrop-blur sm:p-7"><p className="text-xs font-bold uppercase tracking-[.16em] text-white/40">Hana opportunity mode</p><h2 className="mt-2 font-display text-2xl font-semibold">Choose your next quest.</h2><p className="mt-2 max-w-2xl text-sm leading-6 text-white/50">Hana can compare current opportunities by deadline, eligibility, effort, learning value, portfolio value, fit, and entry fee. She should verify changing details from current sources before recommending one.</p><button onClick={()=>navigate(`/chat?prompt=${encodeURIComponent("Browse the latest free-entry opportunities for my selected career path. Find hackathons, Google or other major developer programs, competitions, scholarships, and open-source opportunities. Verify current details from official sources, exclude paid-entry opportunities, rank the strongest few by fit, and explain why each is worth considering.")}`)} className="mt-5 inline-flex items-center gap-2 rounded-full bg-[#f1c77b] px-5 py-3 font-bold text-[#172630]">Ask Hana for latest recommendations <ArrowRight className="h-4 w-4"/></button></section>
  </HanaGameFrame>;
}
