import { ArrowLeft, ArrowRight, BriefcaseBusiness, ExternalLink, HeartHandshake, Sparkles } from "lucide-react";
import { Link } from "wouter";

const opportunities = [
  { title: "Hackathons", description: "Practice shipping a small idea with a team and create portfolio evidence.", url: "https://devpost.com/hackathons", why: "Good for learning by building." },
  { title: "Open-source contributions", description: "Find real repositories where documentation, tests, and beginner-friendly issues can become evidence.", url: "https://github.com/explore", why: "Good for visible engineering experience." },
  { title: "Scholarships & programs", description: "Research university, fellowship, mentorship, and student programs that match your interests.", url: "https://www.opportunitiesforafricans.com/", why: "Good for expanding your learning options." },
];

export default function Opportunities() {
  return <main className="min-h-screen bg-[#FBF7F1] px-5 py-8 text-[#2d3c39] md:px-8"><div className="mx-auto max-w-6xl"><header className="flex items-start justify-between gap-4"><div><p className="text-xs font-bold uppercase tracking-[.16em] text-[#9b8e80]">Opportunity Beacon</p><h1 className="mt-2 font-display text-4xl font-semibold">Find something worth trying.</h1><p className="mt-3 max-w-2xl text-[#76695d]">Hana puts fit before fear. Deadlines can matter, but they don't need to become a countdown.</p></div><Link href="/journey" className="inline-flex items-center gap-2 rounded-full border border-[#dfd3c7] bg-white px-4 py-2 text-sm font-semibold"><ArrowLeft className="h-4 w-4"/>Back</Link></header><section className="mt-8 grid gap-4 md:grid-cols-3">{opportunities.map(item => <article key={item.title} className="rounded-[28px] border border-[#e7ddd2] bg-white p-5 shadow-sm"><div className="flex items-center justify-between"><div className="rounded-2xl bg-[#edf5f0] p-3 text-[#4f806f]"><BriefcaseBusiness className="h-5 w-5"/></div><HeartHandshake className="h-5 w-5 text-[#db8b71]"/></div><h2 className="mt-5 font-display text-2xl font-semibold">{item.title}</h2><p className="mt-2 text-sm leading-6 text-[#76695d]">{item.description}</p><div className="mt-4 rounded-2xl bg-[#fffaf4] p-3 text-sm"><strong>Why explore it:</strong> {item.why}</div><a href={item.url} target="_blank" rel="noreferrer" className="mt-5 inline-flex items-center gap-2 text-sm font-semibold text-[#315d58]">Open opportunity source <ExternalLink className="h-4 w-4"/></a></article>)}</section><section className="mt-6 rounded-[28px] border border-[#e7ddd2] bg-[#f7f1e9] p-6"><Sparkles className="h-5 w-5 text-[#db8b71]"/><h2 className="mt-3 font-display text-2xl font-semibold">A better progress signal</h2><p className="mt-2 max-w-2xl text-sm leading-6 text-[#76695d]">Instead of “you are 73% done”, Hana can show what you have made, what you understand, and what you could try next.</p><Link href="/path" className="mt-5 inline-flex items-center gap-2 rounded-full bg-[#315d58] px-4 py-2.5 text-sm font-semibold text-white">Back to my path <ArrowRight className="h-4 w-4"/></Link></section></div></main>;
}
