import { ArrowRight, ExternalLink, Github, Rocket, Sparkles } from "lucide-react";
import { Link } from "wouter";

const projects = [
  { title: "API Explorer", level: "Starter", description: "Build a tiny app that sends a GET request and displays useful data.", skills: ["HTTP", "JavaScript", "APIs"], url: "https://developer.mozilla.org/en-US/docs/Web/HTTP" },
  { title: "Career Compass", level: "Intermediate", description: "Create a small dashboard that compares skills, roles, and learning resources for a field you care about.", skills: ["React", "Data", "UX"], url: "https://react.dev/learn" },
  { title: "Open Source First Step", level: "Intermediate", description: "Find a beginner-friendly issue, improve documentation, and publish the contribution as evidence.", skills: ["Git", "GitHub", "Communication"], url: "https://github.com/explore" },
];

export default function Projects() {
  return <main className="min-h-screen bg-[#FBF7F1] px-5 py-8 text-[#2d3c39] md:px-8"><div className="mx-auto max-w-6xl"><header className="flex items-start justify-between gap-4"><div><p className="text-xs font-bold uppercase tracking-[.16em] text-[#9b8e80]">Build room</p><h1 className="mt-2 font-display text-4xl font-semibold">One build at a time.</h1><p className="mt-3 max-w-2xl text-[#76695d]">Projects turn learning into evidence. Choose something small enough to finish and useful enough to keep.</p></div><Link href="/" className="rounded-full border border-[#dfd3c7] bg-white px-4 py-2 text-sm font-semibold">Back</Link></header><section className="mt-8 grid gap-4 lg:grid-cols-3">{projects.map((project, index) => <article key={project.title} className="rounded-[28px] border border-[#e7ddd2] bg-white p-5 shadow-sm"><div className="flex items-center justify-between"><div className="rounded-2xl bg-[#edf5f0] p-3 text-[#4f806f]"><Rocket className="h-5 w-5"/></div><span className="text-xs font-bold uppercase tracking-wider text-[#9b8e80]">{project.level}</span></div><h2 className="mt-5 font-display text-2xl font-semibold">{project.title}</h2><p className="mt-2 text-sm leading-6 text-[#76695d]">{project.description}</p><div className="mt-4 flex flex-wrap gap-2">{project.skills.map(skill => <span key={skill} className="rounded-full bg-[#f3eee7] px-3 py-1.5 text-xs font-semibold">{skill}</span>)}</div><a href={project.url} target="_blank" rel="noreferrer" className="mt-6 inline-flex items-center gap-2 text-sm font-semibold text-[#315d58]">Learn the relevant skill <ExternalLink className="h-4 w-4"/></a></article>)}</section><section className="mt-6 rounded-[28px] border border-[#e7ddd2] bg-[#fffaf4] p-6"><div className="flex items-start gap-4"><div className="rounded-2xl bg-white p-3 shadow-sm"><Github className="h-5 w-5"/></div><div><h2 className="font-display text-2xl font-semibold">Make the result visible</h2><p className="mt-2 text-sm leading-6 text-[#76695d]">Keep the code on GitHub, write a short README, and link the finished result from your portfolio. The artifact matters more than a progress percentage.</p><a href="https://skills.github.com/" target="_blank" rel="noreferrer" className="mt-4 inline-flex items-center gap-2 rounded-full bg-[#315d58] px-4 py-2.5 text-sm font-semibold text-white">GitHub Skills <ArrowRight className="h-4 w-4"/></a></div></div></section><div className="mt-6 text-center text-sm text-[#8f8175]"><Sparkles className="mr-1 inline h-4 w-4"/> Hana's rule: make the next thing finishable.</div></div></main>;
}
