import { ArrowRight, ExternalLink, Github, Rocket, Sparkles, Zap, Crown, Bot } from "lucide-react";
import { useLocation } from "wouter";
import HanaGameFrame from "@/components/HanaGameFrame";

const projects = [
  { title: "API Explorer", description: "Learn HTTP and APIs by building a tiny app that fetches and displays useful data.", skills: ["HTTP", "JavaScript", "APIs"], learn: "https://developer.mozilla.org/en-US/docs/Web/HTTP", small: "Build one GET request page with loading and error states.", large: "Build a polished API explorer with search, multiple endpoints, caching, filters, and deployment." },
  { title: "Career Compass", description: "Turn your learning into a useful dashboard that connects skills, roles, resources, and progress.", skills: ["React", "Data", "UX"], learn: "https://react.dev/learn", small: "Build one page that maps three skills to three roles.", large: "Build a personalized career dashboard with roadmap data, resource links, progress, and recommendations." },
  { title: "Open Source First Step", description: "Make a real contribution and turn it into visible engineering evidence.", skills: ["Git", "GitHub", "Communication"], learn: "https://skills.github.com/", small: "Improve one README section or fix one beginner-friendly issue.", large: "Contribute across issues, tests, documentation, and a small feature, then publish a contribution case study." },
];

export default function Projects() {
  const [, navigate] = useLocation();
  const build = (title: string, mode: "Small Quest" | "Grand Quest" | "Build With Hana") => navigate(`/chat?prompt=${encodeURIComponent(`${mode}: ${title}. Build with Hana one milestone at a time. Explain the why, give me a concrete checkpoint after each milestone, keep the scope appropriate for a learner, and help me debug when I get stuck.`)}`);
  return <HanaGameFrame title="Projects · Build evidence">
    <section className="mb-5 min-w-0 rounded-[30px] border border-white/10 bg-white/[.055] p-5 shadow-xl backdrop-blur sm:p-6"><div className="flex min-w-0 items-start gap-3"><Bot className="h-6 w-6 shrink-0 text-[#f1c77b]"/><div className="min-w-0"><p className="text-xs font-bold uppercase tracking-[.16em] text-white/40">Build your proof</p><h2 className="mt-1 break-words font-display text-2xl font-semibold">Turn a learning step into a real quest.</h2><p className="mt-2 break-words text-sm leading-6 text-white/50">Choose a Small Quest for a focused proof, a Grand Quest for portfolio depth, or Build With Hana for a guided deep build.</p></div></div></section>
    <div className="grid min-w-0 gap-5 lg:grid-cols-3">{projects.map(project=><article key={project.title} className="min-w-0 overflow-hidden rounded-[28px] border border-white/10 bg-white/[.055] p-5 shadow-xl backdrop-blur sm:p-6"><div className="flex items-center justify-between"><div className="rounded-2xl bg-[#f1c77b] p-3 text-[#172630]"><Rocket className="h-5 w-5"/></div><Sparkles className="h-5 w-5 text-white/25"/></div><h2 className="mt-5 break-words font-display text-2xl font-semibold">{project.title}</h2><p className="mt-2 break-words text-sm leading-6 text-white/55">{project.description}</p><div className="mt-4 flex flex-wrap gap-2">{project.skills.map(skill=><span key={skill} className="rounded-full border border-white/10 bg-white/5 px-3 py-1.5 text-xs font-semibold text-white/70">{skill}</span>)}</div><a href={project.learn} target="_blank" rel="noopener noreferrer" className="mt-5 inline-flex min-h-10 items-center gap-2 text-sm font-semibold text-[#f1c77b]">Learn the skill <ExternalLink className="h-4 w-4"/></a><div className="mt-5 grid min-w-0 gap-3"><div className="min-w-0 rounded-2xl border border-white/10 bg-[#132434]/70 p-4"><div className="flex items-center gap-2 text-xs font-bold uppercase tracking-wide text-[#f1c77b]"><Zap className="h-4 w-4"/>Small Quest</div><p className="mt-2 break-words text-sm leading-6 text-white/60">{project.small}</p><button onClick={()=>build(project.title,"Small Quest")} className="mt-3 min-h-10 rounded-full bg-white px-3 py-2 text-xs font-bold text-[#172630]">Start Small Quest with Hana</button></div><div className="min-w-0 rounded-2xl border border-white/10 bg-[#132434]/70 p-4"><div className="flex items-center gap-2 text-xs font-bold uppercase tracking-wide text-[#f1c77b]"><Crown className="h-4 w-4"/>Grand Quest</div><p className="mt-2 break-words text-sm leading-6 text-white/60">{project.large}</p><button onClick={()=>build(project.title,"Grand Quest")} className="mt-3 min-h-10 rounded-full bg-[#f1c77b] px-3 py-2 text-xs font-bold text-[#172630]">Start Grand Quest with Hana</button></div></div><button onClick={()=>build(project.title,"Build With Hana")} className="mt-3 inline-flex min-h-10 items-center gap-2 text-xs font-bold text-white/55 underline"><Bot className="h-3.5 w-3.5"/>Build With Hana · deep detailed mode</button></article>)}</div>
    <section className="mt-5 min-w-0 rounded-[30px] border border-white/10 bg-white/[.055] p-6 shadow-xl backdrop-blur sm:p-7"><div className="flex min-w-0 items-start gap-4"><div className="rounded-2xl bg-white p-3 text-[#172630]"><Github className="h-5 w-5"/></div><div className="min-w-0"><p className="text-xs font-bold uppercase tracking-[.16em] text-white/40">Evidence vault</p><h2 className="mt-2 break-words font-display text-2xl font-semibold">Make the result visible.</h2><p className="mt-2 break-words text-sm leading-6 text-white/50">Keep the code on GitHub, write a short README, and link the finished result from your portfolio.</p><a href="https://skills.github.com/" target="_blank" rel="noopener noreferrer" className="mt-4 inline-flex min-h-10 items-center gap-2 rounded-full bg-[#f1c77b] px-4 py-2.5 text-sm font-bold text-[#172630]">GitHub Skills <ArrowRight className="h-4 w-4"/></a></div></div></section>
  </HanaGameFrame>;
}
